import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    'index',
    {
      type: 'category',
      label: 'Examples',
      collapsed: false,
      items: [{ type: 'autogenerated', dirName: 'examples' }],
    },
  ],
  apiSidebar: ['api/index', ...require('./docs/api/typedoc-sidebar.cjs')],
};

export default sidebars;
